inherit_from: .rubocop_todo.yml

require:
  - rubocop-capybara
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable

RSpec/ExampleLength:
  Exclude:
    - spec/system/**/*.rb
    - spec/views/**/*.rb
RSpec/MultipleExpectations:
  Max: 2
  Exclude:
    - spec/system/**/*.rb
    - spec/views/**/*.rb

Style/Documentation:
  Enabled: false
