name: Code linter

on: [push]

jobs:
  rubocop:
    name: "Rubocop ruby style checks"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.1
    - uses: actions/cache@v3
      with:
        path: vendor/bundle
        key: ${{ runner.OS }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.OS }}-gems-
    - name: Install ruby gems
      run: |
        gem install bundler -v 2.4.8 --no-doc
        bundle config path vendor/bundle
        bundle check || bundle install --jobs 4 --retry 3
    - name: Run ruby code style checks
      run: |
        bundle exec rubocop
